name: reversi
version: 0.1.0
description: >
  This package implements the core algorithm for Reversi (Othello).
  You have to code your own UI to program a Reversi game.
  
  This package bundles with a Reversi console program for demo purpose.
author: Michael Chen <cwchen.tw@outlook.com>
homepage: http://github.com/cwchentw/reversi-core-dart
executables:
  reversi:
dependencies:
  algo:
    git: https://github.com/cwchentw/algo-dart.git
dev_dependencies:
  test: "^0.12.20"